services:
  db:
    container_name: merca-shop-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres:/var/lib/postgresql/data 
    ports:
      - '5450:5432'
